# -*- coding: utf-8 -*-
"""mean_var_std.pynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hMmO6z8RULvlzYiP3ldU3qGwdLvur_Z5
"""

import numpy as np

def calculate(input_list):
    if len(input_list) != 9:
        raise ValueError("List must contain nine numbers.")

    matrix = np.array(input_list).reshape(3, 3)
    funcs = ['mean', 'var', 'std', 'max', 'min', 'sum']

    return {func: [getattr(matrix, func)(axis=0).tolist(),
                   getattr(matrix, func)(axis=1).tolist(),
                   getattr(matrix, func)().tolist()] for func in funcs}

result = calculate([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(result)