# -*- coding: utf-8 -*-
"""Sea Level Predictor.pynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hMmO6z8RULvlzYiP3ldU3qGwdLvur_Z5
"""

import pandas as pd
import matplotlib.pyplot as plt
from scipy.stats import linregress

# Load the dataset
df = pd.read_csv('/content/epa-sea-level.csv')

# Create scatter plot
plt.figure(figsize=(10, 6))
plt.scatter(df['Year'], df['CSIRO Adjusted Sea Level'], color='blue', label='Data')

# First line of best fit (using all data)
slope1, intercept1, r_value1, p_value1, std_err1 = linregress(df['Year'], df['CSIRO Adjusted Sea Level'])
years_extended = pd.Series(range(1880, 2051))
sea_level_pred1 = intercept1 + slope1 * years_extended
plt.plot(years_extended, sea_level_pred1, color='green', label='Best Fit Line (1880-2050)')

# Second line of best fit (from year 2000 onwards)
df_recent = df[df['Year'] >= 2000]
slope2, intercept2, r_value2, p_value2, std_err2 = linregress(df_recent['Year'], df_recent['CSIRO Adjusted Sea Level'])
years_recent_extended = pd.Series(range(2000, 2051))
sea_level_pred2 = intercept2 + slope2 * years_recent_extended
plt.plot(years_recent_extended, sea_level_pred2, color='red', label='Best Fit Line (2000-2050)')

# Add labels and title
plt.xlabel('Year')
plt.ylabel('Sea Level (inches)')
plt.title('Rise in Sea Level')
plt.legend()

# Save plot and return figure
plt.savefig('sea_level_plot.png')
plt.show()